### ISSUE TITLE
orthorec

### ISSUE THREAD

**Issue by decarlof** [tomography/tomopy-cli#64]
Looking for suggestion in keeping [orthorec](https://github.com/decarlof/orthorec)  as a stand alone command or include it into tomopy-cli. 

Thoughts?

**Comment by canismarko** [comment]
Slightly off topic but I'll link it to your question at the end.

I think the practice of passing in global "args" to a function should be avoided *as much as possible*. It suffers similar problems as having global state: https://softwareengineering.stackexchange.com/questions/148108/why-is-global-state-so-evil. In my experience working on tomopy-cli, it creates some specific problems:
1. It's not clear from the function signatures which parameters are used for what.
2. Writing tests is more difficult since an argparse.Namespace object has to be created for each test
3. The functions cannot be easily reused (e.g. in jupyter notebooks), again since an argparse.Namespace object has to be created for each test.

Of course, in tomopy-cli, the whole point is to have a shared global state determined by the CLI/config arguments. But given the above, I think the best path is to keep the guts of orthorec separate from the CLI implementation.

Unfortunately that would take some refactoring to separate the two categories of code, but in the end you'd have:
- *orthorec:* a standalone package that implements the orthorec algorithm. I can be agnostic to how it's used, with robust tests. It can also be easily incorporated into other applications (GUIs, etc).
- *tomopy-cli:* handles the messy business of sorting out the command line arguments, and provides a config parameter directing it to use orthorec for try_center, etc. Tomopy-cli then doesn't have to worry about the implementation of orthorec.

**Comment by decarlof** [comment]
good point, orthorec can have  a much broader audience if is a stand alone tool

**Comment by decarlof** [comment]
transferred orthorec to its own repo at  https://github.com/tomography/orthorec
